### PR TITLE
Added a BDD test to prove the bug, with code to fix it.

### LINKED ISSUE #12: As a live cell I will die if I have fewer than two live neighbours does not work
Nice try, but #10 is not complete.
Try this scenario:
```
Scenario: 3x3 grid with one neighbour
  Top left and right has only one neighbour so they will die, center has two and will live.
    Given the grid:
    """
      *.*
      .*.
      ...
    """
    Then the next generation should look like:
    """
      ...
      .*.
      ...
    """
```

### PR DESCRIPTION
**Pull request by fjank**

### CODE REVIEW

**Review by netbrain — DISMISSED** [review]
Looks like a valid test.

File: src/main/java/github/workflow/kata/Grid.java [hunk 1]
```diff
@@ -6,10 +6,69 @@
...
+            }
+            // add a new-line
+            niceDef += '\n';
+        }
+        this.gridDef = niceDef;
+    }
+
+    public void nextGeneration() {
+        // so, lets try to implement the actual code.
+        // not so happy with the implementation, it's "a bit" dirty, but it works. Refactor this later.
```
Comment (netbrain) [inline src/main/java/github/workflow/kata/Grid.java]: later is never

File: src/main/java/github/workflow/kata/Grid.java [hunk 2]
```diff
@@ -6,10 +6,69 @@
  * A gaming grid.
  */
 public class Grid {
-    private final String gridDef;
+    private String gridDef;
```
Comment (netbrain) [inline src/main/java/github/workflow/kata/Grid.java]: There are probably better data structures to represent a grid.

File: src/main/java/github/workflow/kata/Grid.java [hunk 3]
```diff
@@ -6,10 +6,69 @@
...
+                        // cell will die.
+                        newDef += '.';
+                    } else {
+                        // cell will still be alive.
+                        newDef += '*';
+                    }
+                } else {
+                    // cell is dead, it will also be dead next round.
+                    newDef += '.';
+                }
```
Comment (netbrain) [inline src/main/java/github/workflow/kata/Grid.java]: This can probably be extracted to one or more functions

File: src/main/java/github/workflow/kata/Grid.java [hunk 4]
```diff
@@ -6,10 +6,69 @@
...
+
+    public void nextGeneration() {
+        // so, lets try to implement the actual code.
+        // not so happy with the implementation, it's "a bit" dirty, but it works. Refactor this later.
+        String newDef = "";
+        String[] rows = gridDef.split("\n");
+        for (int row = 0; row < rows.length; row++) {
+            char[] cols = rows[row].toCharArray();
+            for (int col = 0; col < cols.length; col++) {
+                char ch = cols[col];
```
Comment (netbrain) [inline src/main/java/github/workflow/kata/Grid.java]:
```suggestion
        for (String row : gridDef.split("\n")) {
            for (char ch :  row.toCharArray()) {
```

File: src/main/java/github/workflow/kata/Grid.java (hunk 2 above)
Comment (netbrain) [reply src/main/java/github/workflow/kata/Grid.java]: would recommend using either a single array with a stride parameter or a 2xdimensional array

File: src/main/java/github/workflow/kata/Grid.java (hunk 1 above)
Comment (fjank) [reply src/main/java/github/workflow/kata/Grid.java]: on it

File: src/main/java/github/workflow/kata/Grid.java (hunk 2 above)
Comment (fjank) [reply src/main/java/github/workflow/kata/Grid.java]: going for 2xdim array, strides are a bit cumbersome.

File: src/main/java/github/workflow/kata/Grid.java (hunk 3 above)
Comment (fjank) [reply src/main/java/github/workflow/kata/Grid.java]: oh yes, that seems appropriate.

File: src/main/java/github/workflow/kata/Grid.java (hunk 4 above)
Comment (fjank) [reply src/main/java/github/workflow/kata/Grid.java]: it looks differend after the refactorings I have done.

**Review by netbrain — APPROVED** [review]
